### ISSUE TITLE
Can we give multiple files to copy to different destinations?

### ISSUE THREAD

**Issue by LakshmiRavali** [dmnemec/copy_file_to_another_repo_action#33]
I am using this github action, It is copying one source  file to one destination directory, Can we give multiple sources and destinations?
My yml file:
```
- name: Pushes test file
uses: dmnemec/copy_file_to_another_repo_action@main
env:
  API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
with:
  source_file: 'test/transfer/'
  destination_repo: 'repo name'
  destination_folder: 'src/destination/'
  user_email: 'email'
  user_name: 'name'
  commit_message: 'A custom message for the commit'
```

**Comment by JoseRodrigues443** [comment]
@LakshmiRavali you can check my example here

https://github.com/JoseRodrigues443/Awesome-CV/blob/master/.github/workflows/main.yml

Basically I use a matrix with key values (location and destination) and with that I can do what you need

```
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: [resume, cv, coverletter]
        include:
          - repo: JoseRodrigues443/JoseRodrigues443
            dir: ''
          - repo: JoseRodrigues443/joserodrigues443.github.io
            dir: static/files
```
