### ISSUE TITLE
Doesn't post to root folder.

### ISSUE THREAD

**Issue by N6REJ** [dmnemec/copy_file_to_another_repo_action#53]
Trying to post files from my [common settings repo](https://github.com/Bearsampp/.settings) so another repo which should have the same files and structure and its not posting to root.  instead its putting it in the 'site' folder.
```
name: File sync

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: '.git-sync/site/*.*'
          user_name: 'Bearsampp'
          user_email: 'programming@hallhome.us'
          destination_repo: 'Bearsampp/website'
          #destination_folder: '/'
          destination_branch: 'main'
```

![image](https://user-images.githubusercontent.com/1850089/145694826-5693ee57-07a1-4a5c-8449-2d15d1fa99cc.png)
