### ISSUE TITLE
Setting up to use default Github env. variables

### ISSUE THREAD

**Issue by damiththa** [dmnemec/copy_file_to_another_repo_action#56]
Instead of having to hard code the `destination_repo`, it might be ideal if this can take default GitHub env. variables. 
Please see below. 
This could come in handy, especially if this `yml` is to be used as a template for multiple repos. 

```
...
    - name: Pushes output to destination repository
      uses: dmnemec/copy_file_to_another_repo_action@main 
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source_file: 'fromFolder/'
        destination_repo: '${GITHUB_REPOSITORY}'
        destination_folder: 'toFolder'
...
```
