### ISSUE TITLE
Fails on cp: target '/tmp/tmp.ahLafm/monorepo-builder' is not a directory

### ISSUE THREAD

**Issue by TomasVotruba** [dmnemec/copy_file_to_another_repo_action#8]
I'm trying to publish full directory (not just single file) to remote repository.

On this Github Actions setup: https://github.com/symplify/symplify/pull/2437/files#diff-c065bcdb0c59642b8340c2b26d8ab09cc27d3ee7859a3575f916a6497cb7a17fR39

```yaml
            -
                name: Push To Remote Repository
                uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
                env:
                    API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
                with:
                    source_file: packages-scoped/${{ matrix.scoped_package }}
                    destination_repo: symplify/${{ matrix.scoped_package }}-prefixed
                    user_email: 'tomas.vot@gmail.com'
                    user_name: 'TomasVotruba'
```

I got this fail:
https://github.com/symplify/symplify/pull/2437/checks?check_run_id=1341352063

![image](https://user-images.githubusercontent.com/924196/97856504-acb7e000-1cfc-11eb-8799-32ac8acdb82f.png)

<br>

Any tips what I'm doing wrong?

Thank you
